- hosts: etcd
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Download etcd archive
      get_url:
        url: "{{ etcdDownloadURL }}"
        dest: /tmp/"{{ etcdFile }}"
        state:

  #   - name: Untar etcd

  #   - name: Create etcd service file

  #   - name: Copy etcd certificate

  #   - name: Copy etcd key

  #   - name: Copy etcd ca-cert.crt

  #   - name: Ensure etcd is running

  # handlers:
  #   - name: Restart etcd
  #     systemd:
  #       name: etcd
  #       state: restarted
  #       daemon_reload: True
  #       enabled: True
  #     listen:
  #       - restart-etcd
