- hosts: localhost
  gather_facts: True
  become: True
  vars_files:
    - vars.yml
  tasks:
    - name: Configure the OKD hosts
      blockinfile:
        path: /etc/ansible/hosts
        block: "{{okdHosts}}"
        state: present

    - name: Configure the etcd hosts
      blockinfile:
        path: /etc/ansible/hosts
        block: "{{etcdHosts}}"
        state: present

    - name: Disable host key checking
      lineinfile:
        path: /etc/ansible/ansible.cfg
        line: 'host_key_checking = False'
        regex: ^#host_key_checking = False'
        state: present
