- hosts: etcd
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Sync the etcd rpm
      copy:
        src: "{{ etcdPath }}/{{ etcdRPM }}"
        dest: /tmp/
        owner: root
        group: root
        mode: 0644

    - name: Install etcd
      yum:
        name: "/tmp/{{ etcdRPM }}"
        state: present
  #   - name: Untar etcd

  #   - name: Create etcd service file

  #   - name: Copy etcd certificate

  #   - name: Copy etcd key

  #   - name: Copy etcd ca-cert.crt

  #   - name: Ensure etcd is running

  # handlers:
  #   - name: Restart etcd
  #     systemd:
  #       name: etcd
  #       state: restarted
  #       daemon_reload: True
  #       enabled: True
  #     listen:
  #       - restart-etcd
