- hosts: etcd
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Set the hostnames
      hostname:
        use: systemd
        name: "{{ inventory_hostname }}"
    - name: Sync the etcd rpm
      copy:
        src: "{{ etcdPath }}/{{ etcdRPM }}"
        dest: /tmp/
        owner: root
        group: root
        mode: 0644

    - name: Install etcd
      yum:
        name: "/tmp/{{ etcdRPM }}"
        state: present
      notify:
        - restart-etcd

    - name: Sync the etcd.conf template
      template:
        src: templates/etcd.j2
        dest: "{{ etcdConfDir }}/etcd.conf"
        owner: etcd
        group: root
        mode: 0644
      notify:
        - restart-etcd

    - name: Ensure that etcd is started
      systemd:
        name: etcd
        state: started
        enabled: True
  #   - name: Untar etcd

  #   - name: Create etcd service file

  #   - name: Copy etcd certificate

  #   - name: Copy etcd key

  #   - name: Copy etcd ca-cert.crt

  #   - name: Ensure etcd is running

  handlers:
    - name: Restart etcd
      systemd:
        name: etcd
        state: restarted
        enabled: True
      listen:
        - restart-etcd
