hostsFile: |
  [etcd]
  etcd-node-1.okd.dev
  etcd-node-2.okd.dev
  etcd-node-3.okd.dev
  [okd]
  okd-node-1.okd.dev
  okd-node-2.okd.dev
  okd-node-3.okd.dev
# This exists to make the code bit more readable
etcdNode1: etcd-node-1.okd.dev
etcdNode2: etcd-node-2.okd.dev
etcdNode3: etcd-node-3.okd.dev
# This path is based on the configuration directory determined from the RPM
# built here: https://github.com/exNihlio/terraform
etcdConfDir: /etc/etcd.d/
etcdDataDir: "/var/lib/etcd"
etcdClientPort: 2379
etcdPeerPort: 2380
etcdPeerMode: "https"
etcdClientMode: "http"
etcdPath: etcd
etcdPeerUrls: "{{etcdPeerMode}}://etcd-node-1.okd.dev:{{etcdPeerPort}},{{etcdMode}}://etcd-node-2.okd.dev:{{etcdPeerPort}},{{etcdPeerMode}}://etcd-node-3.okd.dev:{{etcdPeerPort}}"
etcdClientUrls: "{{etcdClientMode}}://etcd-node-1.okd.dev:{{etcdClientPort}},{{etcdClientMode}}://etcd-node-2.okd.dev:{{etcdClientPort}},{{etcdClientMode}}://etcd-node-3.okd.dev:{{etcdClientPort}}"
etcdDiscoverySRV: "okd.dev"
etcdVer: "v3.4.13-1"
etcdRPM: "etcd-{{ etcdVer }}.x86_64.rpm"
## Enable TLS for etcd
enableTLS: false
etcdWildCard: "*.okd.dev"
## CSR Data
emailAddress: "example@example.com"
countryName: "US"
organizationName: "Example Company"
commonName: "etcd-example-donottrust"
wildcardCommonName: "*.okd.dev"
wildcardKeyName: "star_okd_dev"
wildcardCsrName: "star_okd_dev"
wildcardCrtName: "star_okd_dev"