hostsFile: |
  [etcd]
  etcd-node-1.okd.dev
  etcd-node-2.okd.dev
  etcd-node-3.okd.dev
  [okd]
  okd-node-1.okd.dev
  okd-node-2.okd.dev
  okd-node-3.okd.dev
etcdPath: etcd
etcdVer: "v3.4.13"
etcdRPM: "etcd-{{ etcdVer }}.x86_64.rpm"