- hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update the ansible hosts file
      blockinfile:
        block: "{{ webHosts }}"
        path: "{{ hostsFile }}"
        owner: root
        group: root
        mode: 0644
    - name: Don't validate host keys
      lineinfile:
        line: 'host_key_checking = False'
        regexp: '^#host_key_checking = False'
        state: present
        path: /etc/ansible/ansible.cfg
