- hosts: localhost
  gather_facts: no
  become: yes
  vars:
    - hostsFile: /etc/ansible/hosts
      # Update this variable with your ES hostnames/IPs
      esHosts: |
        [elasticsearch]
        es-node-1.es.dev
        es-node-2.es.dev
        es-node-3.es.dev
  tasks:
    - name: Ensure that the hosts file is updated
      blockinfile:
        path: "{{ hostsFile }}"
        block: "{{ esHosts }}"