- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Copy the ansible_hosts file
      copy:
        src: ansible_hosts
        dest: /etc/ansible/hosts
        owner: root
        mode: 0644

    - name: Disable host key checking
      lineinfile:
        path: /etc/ansible/ansible.cfg
        line: ^host_key_checking = False"
        insertafter: "^#host_key_checking = False"