- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Set the hostname for {{ item }}
      hostname: 
        name: "{{ item }}"
      delegate_to: "{{ item }}"
      run_once: True
      with_items: "{{ hostnames }}"
  