- hosts: all
  become: yes
  gather_facts: yes
  vars:
    hostnames:
      - "node-1.k8s.dev"
      - "node-2.k8s.dev"
      - "node-3.k8s.dev"
  tasks:
    - name: Set the hostname for {{ item }}
      hostname: 
        name: "{{ item }}"
      delegate_to: "{{ item }}"
      run_once: True
      with_items: "{{ hostnames }}"
  