## Do not run install-crio.yml and install-docker.yml together.
- hosts: k8s
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install the libcontainers apt key
      apt_key:
        url: "{{ libcontainer_apt_key_url }}"
        state: present

    - name: Install the libcontainers cri-o apt key
      apt_key: 
        url: "{{ libcontainer_crio_apt_key_url }}"
        state: present

    - name: Install the libcontainers repo
      apt_repository:
        repo: "{{ libcontainer_apt_url }}"
        filename: "devel:kubic:libcontainers:stable"
        update_cache: True
        state: present

    - name: Install the libcontainers cri-o repo
      apt_repository:
        repo: "{{ libcontainer_crio_apt_url }}"
        filename: "devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}"
        update_cache: True
        state: present

    - name: Install cri-o and cri-o-runc
      apt:
        name: "{{ item }}"
        state: present
        update_cache: True
      with_items:
        - cri-o
        - cri-o-runc

    - name: Start crio
      systemd:
        name: crio
        state: started
        enabled: True
        daemon_reload: True
    # Review here: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
    - name: enable net.bridge.bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        state: present
        reload: True

    - name: enable net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        state: present
        reload: True

    - name: enable net.bridge.bridge-nf-call-ip6tables
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
        state: present
        reload: True



