- hosts: k8s
  gather_facts: True
  become: True
  vars_files:
    - vars.yml
  tasks:
    - name: Format the Docker disk
      filesystem:
        dev: "{{ docker_disk }}"
        fstype: "{{ docker_disk_fs_type }}"

    - name: Make the Docker directory
      file:
        path: /var/lib/docker
        state: directory
        mode: 0700

    - name: Mount the Docker disk
      mount:
        path: /var/lib/docker
        src: "{{ docker_disk }}"
        state: mounted
        fstype: "{{ docker_disk_fs_type }}"
        opts: defaults

    - name: Install the Docker apt key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Install the Docker apt repository
      apt_repository:
        repo: "{{ docker_apt_url }}"
        filename: docker
        update_cache: True
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: True
    
    - name: Drop off the Docker daemon.json file
      copy:
        src: files/daemon.json
        dest: /etc/docker/
        owner: root
        group: docker
        mode: 0600
      notify:
        - restart-docker

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: True
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: started
        enabled: True
      listen:
        - restart-docker