- hosts: localhost
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update the ansible hosts file
      blockinfile:
        block: "{{ webHosts }}"
        path: "{{ hostsFile }}"
        owner: root
        group: root
        mode: 0644
        