- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: Update the ansible hosts file
      blockinfile:
        block: "{{ webHosts }}"
        path: "{{ hostFile }}"
        owner: root
        group: root
        mode: 0644
        